services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: pavan
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped
  stalwart-api:
    container_name: stalwart-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/customerdb
    image: pavank1567/customer
    ports:
      - "8081:8080"
    networks:
      - db
    depends_on:
      - db
    restart: unless-stopped


networks:
  db:
    driver: bridge
volumes:
  db: